version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    target-branch: master
    schedule:
      interval: weekly
      day: thursday
      time: "10:30"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "go.mongodb.org/atlas-sdk/*"
    groups:
      golang:
        patterns:
          - "golang.org*"
      google:
        patterns:
          - "*google.golang.org*"
      aws:
        patterns:
          - "github.com/aws*"
      containers:
        patterns:
          - "github.com/containers*"
      otel:
        patterns:
          - "go.opentelemetry.io/otel*"
 