name: run make and push to dependabot PR

on: [pull_request]

permissions: 
  pull-requests: write
  contents: write
  repository-projects: read

jobs:
  run-make:
    name: Run make
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Run make
        run: |
          make gen-purls

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit updated purls.txt if changed
        run: |
          echo "purls.txt changed, committing..."
          git add purls.txt || echo "No purls.txt to add"
          git commit -m "chore: update purls.txt"
          git push
